ManagementByObjectives/Controllers/LoginController.cs
using ManagementByObjectives.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;

namespace ManagementByObjectives.Controllers
{
    public class LoginController : Controller
    {
        HttpClient client;

        public LoginController(IHttpClientFactory factory)
        {
            client = factory.CreateClient();
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Usuario usuario)
        {
            client.BaseAddress = new Uri("http://localhost:5203"); 
            client.DefaultRequestHeaders.Accept.Add(new
                System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json")); 
            try 
            {
                HttpResponseMessage response = client.GetAsync("api/autenticacao/"+usuario.Email +"/" +usuario.Senha).Result;

                if (response.IsSuccessStatusCode)
                {
                    var autenticado = await response.Content.ReadAsStringAsync();
                    //var autenticado = await response.Content.ReadAsAsync<bool[]>();                    
                    return RedirectToAction("Index", "Objetivo");
                }
                else
                {
                    throw new Exception("Ocorreu um erro na autenticação!");
                }

            }
            catch(Exception ex)
            {
                return null; 
            }

        }

    }


}

ManagementByObjectives/Controllers/UsuarioController.cs
using ManagementByObjectives.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;

namespace ManagementByObjectives.Controllers
{
    public class UsuarioController : Controller
    {
        HttpClient client;

        public UsuarioController(IHttpClientFactory factory)
        {
            client = factory.CreateClient();
        }
        public async Task<IActionResult> Listar()
        {
            client.BaseAddress = new Uri("http://localhost:5203");
            client.DefaultRequestHeaders.Accept.Add(new
                System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            try
            {
                HttpResponseMessage response = client.GetAsync("api/usuario").Result;
                if (response.IsSuccessStatusCode)
                {
                    var listaUsuarios = await response.Content.ReadAsAsync<Usuario[]>();
                    return View(listaUsuarios.ToList());
                }
                else
                {
                    throw new Exception("Ocorreu um erro na listagem!");
                }

            }
            catch (Exception ex)
            {
                throw new Exception("Ocorreu um erro na listagem!");
            }
        }

        [HttpGet]
        public IActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Incluir(Usuario usuario)
        {
            try
            {
                usuario.Status = 1;
                usuario.DataCriacao = DateTime.Today;

                client.BaseAddress = new Uri("http://localhost:5203");
                client.DefaultRequestHeaders.Accept.Add(new
                    MediaTypeWithQualityHeaderValue("application/json"));

                // gerar o json a partir do objeto fornecido como parâmetro

                string json = JsonConvert.SerializeObject(usuario);

                // gerar o fluxo de bytes para a API

                HttpContent content = new StringContent(json, Encoding.Unicode, "application/json");

                // enviar o objetivo para a API

                var response = await client.PostAsync("api/usuario", content);


                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Listar");
                }
                else
                {
                    string erro = $"{response.StatusCode} - {response.ReasonPhrase}";
                    throw new Exception(erro);
                }

            }
            catch (Exception ex)
            {
                return View("_Erro", ex);
            }

        }

        [HttpGet]
        public Task<IActionResult> Editar(int id)
        {
            return ProcessarUsuario(id, "Editar");

        }



        private async Task<IActionResult> ProcessarUsuario(int id, string viewName)
        {
            client.BaseAddress = new Uri("http://localhost:5203");
            client.DefaultRequestHeaders.Accept.Add(new
                System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            try
            {
                HttpResponseMessage response = client.GetAsync("api/usuario/" + id).Result;

                if (response.IsSuccessStatusCode)
                {
                    var usuario = await response.Content.ReadAsAsync<Usuario>();
                    //var autenticado = await response.Content.ReadAsAsync<bool[]>();                    
                    return View(viewName, usuario);
                }
                else
                {
                    throw new Exception("Ocorreu um erro na autenticação!");
                }

            }
            catch (Exception ex)
            {
                return View("_Erro", ex);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Editar(Usuario usuario)
        {
            try
            {
                usuario.DataCriacao = DateTime.Today;

                client.BaseAddress = new Uri("http://localhost:5203");
                client.DefaultRequestHeaders.Accept.Add(new
                    MediaTypeWithQualityHeaderValue("application/json"));

                // gerar o json a partir do objeto fornecido como parâmetro

                string json = JsonConvert.SerializeObject(usuario);

                // gerar o fluxo de bytes para a API

                HttpContent content = new StringContent(json, Encoding.Unicode, "application/json");

                // enviar o objetivo para a API

                var response = await client.PutAsync("api/usuario", content);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Listar");
                }
                else
                {
                    string erro = $"{response.StatusCode} - {response.ReasonPhrase}";
                    throw new Exception(erro);
                }

            }
            catch (Exception ex)
            {
                return View("_Erro", ex);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(Usuario usuario)
        {
            try
            {
                usuario.Status = 1;
                usuario.DataCriacao = DateTime.Today;

                client.BaseAddress = new Uri("http://localhost:5203");
                client.DefaultRequestHeaders.Accept.Add(new
                    MediaTypeWithQualityHeaderValue("application/json"));

                // gerar o json a partir do objeto fornecido como parâmetro

                string json = JsonConvert.SerializeObject(usuario);

                // gerar o fluxo de bytes para a API

                HttpContent content = new StringContent(json, Encoding.Unicode, "application/json");

                // enviar o objetivo para a API

                var response = await client.DeleteAsync("api/usuario");

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Listar");
                }
                else
                {
                    string erro = $"{response.StatusCode} - {response.ReasonPhrase}";
                    throw new Exception(erro);
                }

            }
            catch (Exception ex)
            {
                return View("_Erro", ex);
            }

        }
    }
}

ManagementByObjectives/Views/Shared/_Erro.cshtml
@model Exception
@{
    ViewData["Title"] = "_Erro";
}

<h1 class="text-danger">Ocorreu o seguinte erro:</h1>

<div class="alert alert-danger">
    @Model.Message
</div>

ManagementByObjectives/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gerenciamento de Objetivos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ManagementByObjectives.styles.css" asp-append-version="true" />
</head>
<body>

    <div class="area"></div>
    
    <nav class="main-menu">
        <ul>
            <li>
                <a asp-action="Index" asp-controller="Objetivo">
                    <i class="fa fa-home fa-2x"></i>
                    <span class="nav-text">
                        Home
                    </span>
                </a>

            </li>                                  
            <li>
                <a asp-action="Listar" asp-controller="Usuario">
                    <i class="fa fa-user"></i>
                    <span class="nav-text">
                        Usuários Administrativos
                    </span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-cog"></i>
                    <span class="nav-text">
                        Cadastro de Ciclos
                    </span>
                </a>
            </li>   
            <li>
                <a href="#">
                    <i class="fa fa-users"></i>
                    <span class="nav-text">
                        Alteração de Gestor
                    </span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-search"></i>
                    <span class="nav-text">
                        Consulta de Objetivos
                    </span>
                </a>
            </li>            
            <li>
                <a href="#">
                    <i class="fa fa-info fa-2x"></i>
                    <span class="nav-text">
                        Swagger APIs
                    </span>
                </a>
            </li>
        </ul>

        <ul class="logout">
            <li>
                <a asp-action="Index" asp-controller="Login">
                    <i class="fa fa-power-off fa-2x"></i>
                    <span class="nav-text">
                        Logout
                    </span>
                </a>
            </li>
        </ul>
    </nav>
	    
    <br />
    <div class="container">
        <main role="main" class="pb-3">
           
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ManagementByObjectives - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>